ldap_client_packages:

  RedHat-8:
    - openldap
    - openldap-clients
    - sssd
    - sssd-ldap
    - oddjob-mkhomedir
    - openssl-perl
    - sssd-tools

  Centos-8:
    - openldap_clients
    - sssd
    - sssd-ldap
    - oddjob-mkhomedir
    - openssl-perl

  Archlinux-23: # Manjaro
    - sssd
    - nss-pam-ldapd
  Archlinux-24: # Manjaro
    - sssd
    - nss-pam-ldapd

  Fedora-40:
    - sssd
    - sssd-ldap
    - openldap-clients
    - oddjob-mkhomedir

  Debian-12:
    - sssd
    - oddjob-mkhomedir
    - libpam-sss
    - libnss-sss
    - sssd-tools
    - libsss-sudo

ldap_client_services:
  RedHat-8:
    - sssd
    - oddjobd

  Centos-8:
    - sssd
    - oddjobd

  Archlinux-23: # Manjaro
    - sssd
  Archlinux-24: # Manjaro
    - sssd

  Fedora-40:
    - sssd
    - oddjobd

  Debian-12:
    - sssd
    - oddjobd

  Ubuntu-20:
    - sssd
